import React from "https://esm.sh/react@18.3.1";
import * as ReactDOM from "https://esm.sh/react-dom@18.3.1/client";
import htm from "https://esm.sh/htm@3.1.1";
import {
  AnimatePresence,
  motion,
  useInView,
  useReducedMotion,
  useScroll,
  useSpring,
  useTransform
} from "https://esm.sh/framer-motion@11.11.8?deps=react@18.3.1";
import {
  FaArrowRight,
  FaArrowUpRightFromSquare,
  FaBars,
  FaBriefcase,
  FaCheck,
  FaCode,
  FaEnvelope,
  FaGithub,
  FaGraduationCap,
  FaLinkedinIn,
  FaLocationDot,
  FaMoon,
  FaPython,
  FaReact,
  FaRegStar,
  FaRobot,
  FaSun,
  FaXmark,
  FaTrophy,
  FaXTwitter,
  FaDumbbell,
  FaChartLine,
  FaJava,
  FaLaptopCode,
  FaDownload,
  FaPaperPlane,
  FaQuoteLeft,
  FaCalendarDays,
  FaShieldHeart,
  FaBolt,
  FaCloud,
  FaStar
} from "https://esm.sh/react-icons@5.5.0/fa6?deps=react@18.3.1";

const html = htm.bind(React.createElement);

export {
  React,
  ReactDOM,
  AnimatePresence,
  motion,
  useInView,
  useReducedMotion,
  useScroll,
  useSpring,
  useTransform,
  FaArrowRight,
  FaArrowUpRightFromSquare,
  FaBars,
  FaBriefcase,
  FaCheck,
  FaCode,
  FaEnvelope,
  FaGithub,
  FaGraduationCap,
  FaLinkedinIn,
  FaLocationDot,
  FaMoon,
  FaPython,
  FaReact,
  FaRegStar,
  FaRobot,
  FaSun,
  FaXmark,
  FaTrophy,
  FaXTwitter,
  FaDumbbell,
  FaChartLine,
  FaJava,
  FaLaptopCode,
  FaDownload,
  FaPaperPlane,
  FaQuoteLeft,
  FaCalendarDays,
  FaShieldHeart,
  FaBolt,
  FaCloud,
  FaStar
};

export { html };
